cropbox_filter_node:
  ros__parameters:
    input_cloud: "/velodyne_points"
    output_cloud: "/filtered/velodyne_points"
    min_x: -0.5
    min_y: -0.5
    min_z: -0.5
    max_x: 0.5
    max_y: 0.5
    max_z: 0.5
    leaf_size: 0.01
